import { PokemonType, TrainerCategory, CardRarity, FoilEffect, MoveTheme, PokemonCardData, TrainerCardData } from '../types';

export interface TypeMeta {
  id: PokemonType;
  name: string;
  jpName: string;
  bgGradient: string;
  frameGradient: string;
  primaryColor: string;
  accentColor: string;
  textColor: string;
  badgeBg: string;
}

export const TYPE_CONFIG: Record<PokemonType, TypeMeta> = {
  grass: {
    id: 'grass',
    name: 'Grass',
    jpName: '草',
    bgGradient: 'from-emerald-700 via-green-600 to-emerald-800',
    frameGradient: 'from-emerald-600 via-green-500 to-lime-600',
    primaryColor: '#16a34a',
    accentColor: '#4ade80',
    textColor: '#ffffff',
    badgeBg: '#15803d',
  },
  fire: {
    id: 'fire',
    name: 'Fire',
    jpName: '炎',
    bgGradient: 'from-amber-700 via-red-600 to-orange-800',
    frameGradient: 'from-orange-600 via-red-500 to-amber-500',
    primaryColor: '#ea580c',
    accentColor: '#fb923c',
    textColor: '#ffffff',
    badgeBg: '#c2410c',
  },
  water: {
    id: 'water',
    name: 'Water',
    jpName: '水',
    bgGradient: 'from-blue-700 via-cyan-600 to-sky-800',
    frameGradient: 'from-blue-600 via-sky-500 to-cyan-500',
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    textColor: '#ffffff',
    badgeBg: '#0369a1',
  },
  lightning: {
    id: 'lightning',
    name: 'Lightning',
    jpName: '雷',
    bgGradient: 'from-yellow-600 via-amber-500 to-yellow-700',
    frameGradient: 'from-amber-500 via-yellow-400 to-amber-600',
    primaryColor: '#ca8a04',
    accentColor: '#facc15',
    textColor: '#ffffff',
    badgeBg: '#a16207',
  },
  psychic: {
    id: 'psychic',
    name: 'Psychic',
    jpName: '超',
    bgGradient: 'from-purple-800 via-fuchsia-700 to-pink-800',
    frameGradient: 'from-purple-600 via-fuchsia-500 to-pink-600',
    primaryColor: '#9333ea',
    accentColor: '#c084fc',
    textColor: '#ffffff',
    badgeBg: '#7e22ce',
  },
  fighting: {
    id: 'fighting',
    name: 'Fighting',
    jpName: '闘',
    bgGradient: 'from-stone-800 via-amber-900 to-yellow-950',
    frameGradient: 'from-amber-800 via-orange-800 to-stone-700',
    primaryColor: '#b45309',
    accentColor: '#d97706',
    textColor: '#ffffff',
    badgeBg: '#78350f',
  },
  darkness: {
    id: 'darkness',
    name: 'Darkness',
    jpName: '悪',
    bgGradient: 'from-slate-900 via-zinc-800 to-neutral-900',
    frameGradient: 'from-zinc-800 via-neutral-700 to-slate-900',
    primaryColor: '#27272a',
    accentColor: '#71717a',
    textColor: '#ffffff',
    badgeBg: '#18181b',
  },
  metal: {
    id: 'metal',
    name: 'Metal',
    jpName: '鋼',
    bgGradient: 'from-slate-600 via-zinc-500 to-slate-700',
    frameGradient: 'from-slate-400 via-zinc-300 to-slate-500',
    primaryColor: '#64748b',
    accentColor: '#cbd5e1',
    textColor: '#ffffff',
    badgeBg: '#475569',
  },
  dragon: {
    id: 'dragon',
    name: 'Dragon',
    jpName: 'ドラゴン',
    bgGradient: 'from-amber-700 via-emerald-800 to-yellow-800',
    frameGradient: 'from-amber-600 via-yellow-500 to-emerald-700',
    primaryColor: '#854d0e',
    accentColor: '#eab308',
    textColor: '#ffffff',
    badgeBg: '#713f12',
  },
  fairy: {
    id: 'fairy',
    name: 'Fairy',
    jpName: 'フェアリー',
    bgGradient: 'from-pink-600 via-rose-500 to-pink-700',
    frameGradient: 'from-pink-500 via-rose-400 to-fuchsia-400',
    primaryColor: '#db2777',
    accentColor: '#f472b6',
    textColor: '#ffffff',
    badgeBg: '#be185d',
  },
  colorless: {
    id: 'colorless',
    name: 'Colorless',
    jpName: '無色',
    bgGradient: 'from-slate-300 via-zinc-200 to-gray-300',
    frameGradient: 'from-zinc-300 via-slate-200 to-stone-300',
    primaryColor: '#9ca3af',
    accentColor: '#e5e7eb',
    textColor: '#1f2937',
    badgeBg: '#d1d5db',
  },
};

export const TRAINER_CATEGORY_CONFIG: Record<TrainerCategory, {
  name: string;
  jpName: string;
  color: string;
  gradient: string;
  bannerColor: string;
  defaultRule: string;
}> = {
  supporter: {
    name: 'Supporter',
    jpName: 'サポート',
    color: '#ea580c',
    gradient: 'from-orange-600 via-amber-500 to-red-600',
    bannerColor: '#c2410c',
    defaultRule: 'サポートは、自分の番に1枚しか使えない。',
  },
  item: {
    name: 'Item',
    jpName: 'グッズ',
    color: '#0284c7',
    gradient: 'from-blue-600 via-cyan-500 to-sky-600',
    bannerColor: '#0369a1',
    defaultRule: 'グッズは、自分の番に何枚でも使える。',
  },
  stadium: {
    name: 'Stadium',
    jpName: 'スタジアム',
    color: '#16a34a',
    gradient: 'from-emerald-600 via-green-500 to-teal-600',
    bannerColor: '#15803d',
    defaultRule: 'スタジアムは、自分の番に1枚だけ、バトル場の横に出せる。別の名前のスタジアムが場に出たなら、このカードをトラッシュする。',
  },
  tool: {
    name: 'Pokémon Tool',
    jpName: 'ポケモンのどうぐ',
    color: '#9333ea',
    gradient: 'from-purple-600 via-fuchsia-500 to-violet-600',
    bannerColor: '#7e22ce',
    defaultRule: 'ポケモンのどうぐは、自分のポケモンにつけて使う。ポケモン1匹につき1枚だけつけられ、つけたままにする。',
  },
  ace_spec: {
    name: 'ACE SPEC',
    jpName: 'ACE SPEC',
    color: '#db2777',
    gradient: 'from-fuchsia-600 via-pink-500 to-rose-600',
    bannerColor: '#9d174d',
    defaultRule: 'ACE SPECのカードは、デッキに1枚しか入れられない。',
  },
};

export const RARITY_OPTIONS: { value: CardRarity; label: string; symbol: string }[] = [
  { value: 'C', label: 'C (コモン)', symbol: '●' },
  { value: 'U', label: 'U (アンコモン)', symbol: '◆' },
  { value: 'R', label: 'R (レア)', symbol: '★' },
  { value: 'RR', label: 'RR (ダブルレア)', symbol: 'RR' },
  { value: 'AR', label: 'AR (アートレア)', symbol: 'AR' },
  { value: 'SR', label: 'SR (スーパーレア)', symbol: 'SR' },
  { value: 'SAR', label: 'SAR (スペシャルアートレア)', symbol: 'SAR' },
  { value: 'UR', label: 'UR (ウルトラレア)', symbol: 'UR' },
  { value: 'PROMO', label: 'PROMO (プロモ)', symbol: 'PROMO' },
];

export const FOIL_OPTIONS: { value: FoilEffect; label: string; desc: string }[] = [
  { value: 'none', label: 'ノーマル', desc: '通常のマット仕上げ' },
  { value: 'holo', label: 'ホログラム (キラ)', desc: 'プリズム・ホロフォイルの光沢' },
  { value: 'sparkle', label: 'かがやくキラ (ラメ)', desc: '微細なダイヤモンドスター輝き' },
  { value: 'rainbow', label: 'SAR・レインボー', desc: '七色に変化するスペクトラム光彩' },
  { value: 'gold', label: 'UR・ゴールド', desc: '重厚感のある黄金フレーム＆箔押し' },
  { value: 'tera', label: 'テラスタル・クリスタル', desc: '宝石のような結晶の煌めき' },
  { value: 'dark', label: 'ダークネス・シャドウ', desc: '漆黒のオーラが漂う特別仕様' },
];

export const MOVE_THEME_OPTIONS: { value: MoveTheme; label: string; desc: string }[] = [
  { value: 'standard', label: '通常レイアウト', desc: '標準的な技表示' },
  { value: 'elemental', label: '属性オーラ', desc: '技のタイプに応じたエフェクト背景' },
  { value: 'burst', label: 'バーストスラッシュ', desc: '躍動感あるインパクトエフェクト' },
  { value: 'aura', label: 'エネルギーオーラ', desc: '高出力エネルギーの光彩' },
  { value: 'cosmic', label: 'コズミック・星彩', desc: '宇宙のような星屑グラデーション' },
  { value: 'gilded', label: '金箔・特別な技', desc: '特別なフィニッシュ技用のゴールド装飾' },
];

export const STAGE_OPTIONS: PokemonCardData['stage'][] = [
  'たね',
  '1進化',
  '2進化',
];

// Sample Illustrations (SVG Data URLs for crisp, instantly available card art)
export const SAMPLE_ARTWORKS = [
  {
    id: 'electric_mouse',
    name: '電撃の相棒',
    category: 'pokemon',
    url: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'flame_dragon',
    name: '灼熱のドラゴン',
    category: 'pokemon',
    url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'ocean_mystic',
    name: '深海の守護者',
    category: 'pokemon',
    url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'forest_guardian',
    name: '翠緑の精霊',
    category: 'pokemon',
    url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'psychic_shadow',
    name: '次元の幻影',
    category: 'pokemon',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'trainer_girl',
    name: 'アイドルジムリーダー',
    category: 'trainer',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'trainer_prof',
    name: 'ポケモン博士の研究室',
    category: 'trainer',
    url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'item_device',
    name: '特製ハイパーボール',
    category: 'trainer',
    url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
  },
];

export const PRESET_CARDS: { id: string; name: string; tag: string; data: PokemonCardData | TrainerCardData }[] = [
  {
    id: 'preset_varoom',
    name: 'ブロロン (鋼タイプ定番)',
    tag: 'たねポケモン (鋼)',
    data: {
      kind: 'pokemon',
      id: 'p_varoom',
      name: 'ブロロン',
      suffix: '',
      hp: '60',
      primaryType: 'metal',
      stage: 'たね',
      dexSpecies: 'たんきとうポケモン',
      dexHeight: '1.0m',
      dexWeight: '35.0kg',
      dexNumber: 'NO.0965',
      imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80',
      imageScale: 1.0,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      ability: {
        enabled: false,
        name: '',
        type: 'ability',
        description: '',
      },
      moves: [
        {
          id: 'm1',
          name: 'どくガス',
          energyCost: ['colorless'],
          damage: '',
          description: '相手のバトルポケモンをどくにする。',
          theme: 'standard',
        },
      ],
      weaknessType: 'fire',
      weaknessValue: '×2',
      resistanceType: 'grass',
      resistanceValue: '-30',
      retreatCost: 1,
      flavorText: 'スクラップ工場に 放置された エンジンに 謎の 毒ポケモンが 入り込んで 生まれたと 言われる。',
      illustrator: 'Shin Nagasawa',
      cardNumber: '059/078',
      setSymbol: 'sv1S',
      regulationMark: 'G',
      rarity: 'C',
      foilEffect: 'none',
      selectedFrame: 'normal',
    },
  },
  {
    id: 'preset_lotad',
    name: 'ハスボー (水タイプ定番)',
    tag: 'たねポケモン (水)',
    data: {
      kind: 'pokemon',
      id: 'p_lotad',
      name: 'ハスボー',
      suffix: '',
      hp: '60',
      primaryType: 'water',
      stage: 'たね',
      dexSpecies: 'うきくさポケモン',
      dexHeight: '0.5m',
      dexWeight: '2.6kg',
      dexNumber: 'NO.270',
      imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
      imageScale: 1.0,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      ability: {
        enabled: false,
        name: '',
        type: 'ability',
        description: '',
      },
      moves: [
        {
          id: 'm1',
          name: 'なかまをよぶ',
          energyCost: ['colorless'],
          damage: '',
          description: '自分の山札からたねポケモンを2枚まで選び、ベンチに出す。そして山札を切る。',
          theme: 'standard',
        },
        {
          id: 'm2',
          name: 'みずかけ',
          energyCost: ['water', 'colorless'],
          damage: '20',
          description: '',
          theme: 'standard',
        },
      ],
      weaknessType: 'lightning',
      weaknessValue: '×2',
      resistanceType: 'none',
      resistanceValue: '-30',
      retreatCost: 1,
      flavorText: '葉っぱが 大きく なりすぎて 重くなって しまったため 水に 浮かんで 暮らすように なった。',
      illustrator: 'Teeziro',
      cardNumber: '002/067',
      setSymbol: 'S7D',
      regulationMark: 'E',
      rarity: 'C',
      foilEffect: 'none',
      selectedFrame: 'normal',
    },
  },
  {
    id: 'preset_pikachu_ex',
    name: 'ピカチュウex',
    tag: 'exポケモン (雷)',
    data: {
      kind: 'pokemon',
      id: 'p_pika_ex',
      name: 'ピカチュウ',
      suffix: 'ex',
      hp: '200',
      primaryType: 'lightning',
      stage: 'たね',
      dexSpecies: 'ねずみポケモン',
      dexHeight: '0.4m',
      dexWeight: '6.0kg',
      dexNumber: 'NO. 0025',
      imageUrl: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&auto=format&fit=crop&q=80',
      imageScale: 1.05,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      ability: {
        enabled: true,
        name: 'がんばりハート',
        type: 'ability',
        description: 'このポケモンのHPがまんたんの状態で、相手のポケモンからワザのダメージを受けてきぜつするとき、このポケモンはきぜつせず、HPが「10」の状態で場に残る。',
      },
      moves: [
        {
          id: 'm1',
          name: 'トパーズボルト',
          energyCost: ['grass', 'lightning', 'metal'],
          damage: '300',
          description: 'このポケモンについているエネルギーを3個選び、トラッシュする。',
          theme: 'burst',
          isSpecialMove: true,
          specialTag: 'テラスタルバースト',
        },
      ],
      weaknessType: 'fighting',
      weaknessValue: '×2',
      resistanceType: 'none',
      resistanceValue: '-30',
      retreatCost: 1,
      flavorText: '電気を 溜め込む 性質。ピカチュウが 群れると そこに 雷雲が 発生するという。',
      illustrator: '5ban Graphics',
      cardNumber: '033/106',
      setSymbol: 'SV8',
      regulationMark: 'H',
      rarity: 'RR',
      foilEffect: 'sparkle',
      customCardTag: 'テラスタル',
    },
  },
  {
    id: 'preset_charizard_ex',
    name: 'リザードンex',
    tag: '2進化ex (悪テラスタル)',
    data: {
      kind: 'pokemon',
      id: 'p_char_ex',
      name: 'リザードン',
      suffix: 'ex',
      hp: '330',
      primaryType: 'darkness',
      secondaryType: 'fire',
      stage: '2進化',
      evolvesFrom: 'リザードから進化',
      dexSpecies: 'かえんポケモン',
      dexHeight: '1.7m',
      dexWeight: '90.5kg',
      dexNumber: 'NO. 0006',
      imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
      imageScale: 1.1,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      ability: {
        enabled: true,
        name: 'れんごくしはい',
        type: 'ability',
        description: '自分の番に、このカードを手札から出して進化させたとき、1回使える。自分の山札から「基本炎エネルギー」を3枚まで選び、自分のポケモンに好きなようにつける。そして山札を切る。',
      },
      moves: [
        {
          id: 'm1',
          name: 'バーニングダーク',
          energyCost: ['fire', 'fire'],
          damage: '180+',
          description: '相手がすでにとったサイドの枚数×30ダメージ追加。',
          theme: 'elemental',
          isSpecialMove: false,
        },
      ],
      weaknessType: 'grass',
      weaknessValue: '×2',
      resistanceType: 'none',
      resistanceValue: '-30',
      retreatCost: 2,
      flavorText: '強い 相手を 求めて 飛び回り 何でも 溶かす 高熱の 炎を 吐き出す。',
      illustrator: 'PLANETA Mochizuki',
      cardNumber: '066/108',
      setSymbol: 'SV3',
      regulationMark: 'G',
      rarity: 'SAR',
      foilEffect: 'rainbow',
      customCardTag: '悪テラスタル',
    },
  },
  {
    id: 'preset_mewtwo',
    name: 'ミュウツー',
    tag: '伝説ポケモン (超)',
    data: {
      kind: 'pokemon',
      id: 'p_mewtwo',
      name: 'ミュウツー',
      suffix: '',
      hp: '130',
      primaryType: 'psychic',
      stage: 'たね',
      dexSpecies: 'いでんしポケモン',
      dexHeight: '2.0m',
      dexWeight: '122.0kg',
      dexNumber: 'NO. 0150',
      imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
      imageScale: 1.0,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      ability: {
        enabled: false,
        name: '',
        type: 'ability',
        description: '',
      },
      moves: [
        {
          id: 'm1',
          name: 'サイコキネシス',
          energyCost: ['psychic', 'colorless'],
          damage: '50+',
          description: '相手のバトルポケモンについているエネルギーの数×30ダメージ追加。',
          theme: 'aura',
        },
        {
          id: 'm2',
          name: 'サイコストライク',
          energyCost: ['psychic', 'psychic', 'colorless'],
          damage: '130',
          description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
          theme: 'cosmic',
          isSpecialMove: true,
          specialTag: '秘奥義',
        },
      ],
      weaknessType: 'darkness',
      weaknessValue: '×2',
      resistanceType: 'fighting',
      resistanceValue: '-30',
      retreatCost: 2,
      flavorText: '研究者によって 遺伝子を 組み換えられた 結果 極めて 荒々しい 心を 持つようになった。',
      illustrator: 'Ken Sugimori',
      cardNumber: '071/165',
      setSymbol: 'SV2a',
      regulationMark: 'G',
      rarity: 'R',
      foilEffect: 'holo',
    },
  },
  {
    id: 'preset_iono',
    name: 'ナンジャモ',
    tag: 'サポート (SAR風)',
    data: {
      kind: 'trainer',
      id: 't_iono',
      name: 'ナンジャモ',
      category: 'supporter',
      imageUrl: '',
      imageScale: 1.15,
      imagePositionX: 0,
      imagePositionY: -5,
      imageFit: 'cover',
      isFullArt: false,
      ruleText: 'サポートは、自分の番に1枚しか使えない。',
      effectText: 'お互いのプレイヤーは、それぞれ自分の手札をすべてウラにして切り、山札の下にもどす。\nその後、それぞれ自分のサイドの残り枚数ぶん、山札を引く。',
      subEffectText: 'ハッコウシティのジムリーダー兼超人気インフルエンサー「ドンナモンジャTV」配信者！',
      illustrator: 'kirisAki',
      cardNumber: '096/071',
      setSymbol: 'SV2D',
      regulationMark: 'G',
      rarity: 'SAR',
      foilEffect: 'rainbow',
      customCardTag: 'フルアート',
    },
  },
  {
    id: 'preset_candy',
    name: 'ふしぎなアメ',
    tag: 'グッズ (定番)',
    data: {
      kind: 'trainer',
      id: 't_candy',
      name: 'ふしぎなアメ',
      category: 'item',
      imageUrl: '',
      imageScale: 1.0,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      isFullArt: false,
      ruleText: 'グッズは、自分の番に何枚でも使える。',
      effectText: '自分の手札から2進化ポケモンを1枚選び、そのポケモンへと進化する自分の場の「たねポケモン」の上にのせ、2進化させる。（最初の自分の番や、出したばかりのたねポケモンには使えない。）',
      illustrator: 'Toyste Beach',
      cardNumber: '128/165',
      setSymbol: 'SV2a',
      regulationMark: 'G',
      rarity: 'U',
      foilEffect: 'none',
    },
  },
  {
    id: 'preset_prime_catcher',
    name: 'プライムキャッチャー',
    tag: 'ACE SPEC (グッズ)',
    data: {
      kind: 'trainer',
      id: 't_prime',
      name: 'プライムキャッチャー',
      category: 'ace_spec',
      imageUrl: '',
      imageScale: 1.0,
      imagePositionX: 0,
      imagePositionY: 0,
      imageFit: 'cover',
      isFullArt: true,
      ruleText: 'ACE SPECのカードは、デッキに1枚しか入れられない。',
      effectText: '相手のベンチポケモンを1匹選び、バトルポケモンと入れ替える。その後、自分のバトルポケモンをベンチポケモンと入れ替える。',
      illustrator: 'Studio Bora Inc.',
      cardNumber: '062/071',
      setSymbol: 'SV5K',
      regulationMark: 'H',
      rarity: 'UR',
      foilEffect: 'gold',
      customCardTag: 'ACE SPEC',
    },
  },
];
